/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperationsVehiclesRouteImport } from './routes/operations.vehicles'
import { Route as OperationsFeedingRouteImport } from './routes/operations.feeding'
import { Route as OperationsElectricityRouteImport } from './routes/operations.electricity'
import { Route as OperationsCanteenRouteImport } from './routes/operations.canteen'
import { Route as OperationsAttendanceRouteImport } from './routes/operations.attendance'
import { Route as MastersWorkersRouteImport } from './routes/masters.workers'
import { Route as MastersSuppliersRouteImport } from './routes/masters.suppliers'
import { Route as MastersStockRouteImport } from './routes/masters.stock'
import { Route as MastersSitesRouteImport } from './routes/masters.sites'
import { Route as MastersPondsRouteImport } from './routes/masters.ponds'
import { Route as MastersOwnersRouteImport } from './routes/masters.owners'
import { Route as MastersLedgersRouteImport } from './routes/masters.ledgers'
import { Route as MastersCostcentresRouteImport } from './routes/masters.costcentres'
import { Route as MastersBuyersRouteImport } from './routes/masters.buyers'
import { Route as FinanceTallyRouteImport } from './routes/finance.tally'
import { Route as FinancePurchasesRouteImport } from './routes/finance.purchases'
import { Route as FinancePaymentsRouteImport } from './routes/finance.payments'
import { Route as FinanceLeaseRouteImport } from './routes/finance.lease'
import { Route as FinanceHarvestRouteImport } from './routes/finance.harvest'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsVehiclesRoute = OperationsVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsFeedingRoute = OperationsFeedingRouteImport.update({
  id: '/feeding',
  path: '/feeding',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsElectricityRoute = OperationsElectricityRouteImport.update({
  id: '/electricity',
  path: '/electricity',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsCanteenRoute = OperationsCanteenRouteImport.update({
  id: '/canteen',
  path: '/canteen',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsAttendanceRoute = OperationsAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => OperationsRoute,
} as any)
const MastersWorkersRoute = MastersWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => MastersRoute,
} as any)
const MastersSuppliersRoute = MastersSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => MastersRoute,
} as any)
const MastersStockRoute = MastersStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => MastersRoute,
} as any)
const MastersSitesRoute = MastersSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => MastersRoute,
} as any)
const MastersPondsRoute = MastersPondsRouteImport.update({
  id: '/ponds',
  path: '/ponds',
  getParentRoute: () => MastersRoute,
} as any)
const MastersOwnersRoute = MastersOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => MastersRoute,
} as any)
const MastersLedgersRoute = MastersLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => MastersRoute,
} as any)
const MastersCostcentresRoute = MastersCostcentresRouteImport.update({
  id: '/costcentres',
  path: '/costcentres',
  getParentRoute: () => MastersRoute,
} as any)
const MastersBuyersRoute = MastersBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => MastersRoute,
} as any)
const FinanceTallyRoute = FinanceTallyRouteImport.update({
  id: '/tally',
  path: '/tally',
  getParentRoute: () => FinanceRoute,
} as any)
const FinancePurchasesRoute = FinancePurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => FinanceRoute,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceLeaseRoute = FinanceLeaseRouteImport.update({
  id: '/lease',
  path: '/lease',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceHarvestRoute = FinanceHarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => FinanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/login': typeof LoginRoute
  '/masters': typeof MastersRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/finance/harvest': typeof FinanceHarvestRoute
  '/finance/lease': typeof FinanceLeaseRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/purchases': typeof FinancePurchasesRoute
  '/finance/tally': typeof FinanceTallyRoute
  '/masters/buyers': typeof MastersBuyersRoute
  '/masters/costcentres': typeof MastersCostcentresRoute
  '/masters/ledgers': typeof MastersLedgersRoute
  '/masters/owners': typeof MastersOwnersRoute
  '/masters/ponds': typeof MastersPondsRoute
  '/masters/sites': typeof MastersSitesRoute
  '/masters/stock': typeof MastersStockRoute
  '/masters/suppliers': typeof MastersSuppliersRoute
  '/masters/workers': typeof MastersWorkersRoute
  '/operations/attendance': typeof OperationsAttendanceRoute
  '/operations/canteen': typeof OperationsCanteenRoute
  '/operations/electricity': typeof OperationsElectricityRoute
  '/operations/feeding': typeof OperationsFeedingRoute
  '/operations/vehicles': typeof OperationsVehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/login': typeof LoginRoute
  '/masters': typeof MastersRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/finance/harvest': typeof FinanceHarvestRoute
  '/finance/lease': typeof FinanceLeaseRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/purchases': typeof FinancePurchasesRoute
  '/finance/tally': typeof FinanceTallyRoute
  '/masters/buyers': typeof MastersBuyersRoute
  '/masters/costcentres': typeof MastersCostcentresRoute
  '/masters/ledgers': typeof MastersLedgersRoute
  '/masters/owners': typeof MastersOwnersRoute
  '/masters/ponds': typeof MastersPondsRoute
  '/masters/sites': typeof MastersSitesRoute
  '/masters/stock': typeof MastersStockRoute
  '/masters/suppliers': typeof MastersSuppliersRoute
  '/masters/workers': typeof MastersWorkersRoute
  '/operations/attendance': typeof OperationsAttendanceRoute
  '/operations/canteen': typeof OperationsCanteenRoute
  '/operations/electricity': typeof OperationsElectricityRoute
  '/operations/feeding': typeof OperationsFeedingRoute
  '/operations/vehicles': typeof OperationsVehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/login': typeof LoginRoute
  '/masters': typeof MastersRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/finance/harvest': typeof FinanceHarvestRoute
  '/finance/lease': typeof FinanceLeaseRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/purchases': typeof FinancePurchasesRoute
  '/finance/tally': typeof FinanceTallyRoute
  '/masters/buyers': typeof MastersBuyersRoute
  '/masters/costcentres': typeof MastersCostcentresRoute
  '/masters/ledgers': typeof MastersLedgersRoute
  '/masters/owners': typeof MastersOwnersRoute
  '/masters/ponds': typeof MastersPondsRoute
  '/masters/sites': typeof MastersSitesRoute
  '/masters/stock': typeof MastersStockRoute
  '/masters/suppliers': typeof MastersSuppliersRoute
  '/masters/workers': typeof MastersWorkersRoute
  '/operations/attendance': typeof OperationsAttendanceRoute
  '/operations/canteen': typeof OperationsCanteenRoute
  '/operations/electricity': typeof OperationsElectricityRoute
  '/operations/feeding': typeof OperationsFeedingRoute
  '/operations/vehicles': typeof OperationsVehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/login'
    | '/masters'
    | '/operations'
    | '/register'
    | '/reports'
    | '/finance/harvest'
    | '/finance/lease'
    | '/finance/payments'
    | '/finance/purchases'
    | '/finance/tally'
    | '/masters/buyers'
    | '/masters/costcentres'
    | '/masters/ledgers'
    | '/masters/owners'
    | '/masters/ponds'
    | '/masters/sites'
    | '/masters/stock'
    | '/masters/suppliers'
    | '/masters/workers'
    | '/operations/attendance'
    | '/operations/canteen'
    | '/operations/electricity'
    | '/operations/feeding'
    | '/operations/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance'
    | '/login'
    | '/masters'
    | '/operations'
    | '/register'
    | '/reports'
    | '/finance/harvest'
    | '/finance/lease'
    | '/finance/payments'
    | '/finance/purchases'
    | '/finance/tally'
    | '/masters/buyers'
    | '/masters/costcentres'
    | '/masters/ledgers'
    | '/masters/owners'
    | '/masters/ponds'
    | '/masters/sites'
    | '/masters/stock'
    | '/masters/suppliers'
    | '/masters/workers'
    | '/operations/attendance'
    | '/operations/canteen'
    | '/operations/electricity'
    | '/operations/feeding'
    | '/operations/vehicles'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/login'
    | '/masters'
    | '/operations'
    | '/register'
    | '/reports'
    | '/finance/harvest'
    | '/finance/lease'
    | '/finance/payments'
    | '/finance/purchases'
    | '/finance/tally'
    | '/masters/buyers'
    | '/masters/costcentres'
    | '/masters/ledgers'
    | '/masters/owners'
    | '/masters/ponds'
    | '/masters/sites'
    | '/masters/stock'
    | '/masters/suppliers'
    | '/masters/workers'
    | '/operations/attendance'
    | '/operations/canteen'
    | '/operations/electricity'
    | '/operations/feeding'
    | '/operations/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  LoginRoute: typeof LoginRoute
  MastersRoute: typeof MastersRouteWithChildren
  OperationsRoute: typeof OperationsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/vehicles': {
      id: '/operations/vehicles'
      path: '/vehicles'
      fullPath: '/operations/vehicles'
      preLoaderRoute: typeof OperationsVehiclesRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/feeding': {
      id: '/operations/feeding'
      path: '/feeding'
      fullPath: '/operations/feeding'
      preLoaderRoute: typeof OperationsFeedingRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/electricity': {
      id: '/operations/electricity'
      path: '/electricity'
      fullPath: '/operations/electricity'
      preLoaderRoute: typeof OperationsElectricityRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/canteen': {
      id: '/operations/canteen'
      path: '/canteen'
      fullPath: '/operations/canteen'
      preLoaderRoute: typeof OperationsCanteenRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/attendance': {
      id: '/operations/attendance'
      path: '/attendance'
      fullPath: '/operations/attendance'
      preLoaderRoute: typeof OperationsAttendanceRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/masters/workers': {
      id: '/masters/workers'
      path: '/workers'
      fullPath: '/masters/workers'
      preLoaderRoute: typeof MastersWorkersRouteImport
      parentRoute: typeof MastersRoute
    }
    '/masters/suppliers': {
      id: '/masters/suppliers'
      path: '/suppliers'
      fullPath: '/masters/suppliers'
      preLoaderRoute: typeof MastersSuppliersRouteImport
      parentRoute: typeof MastersRoute
    }
    '/masters/stock': {
      id: '/masters/stock'
      path: '/stock'
      fullPath: '/masters/stock'
      preLoaderRoute: typeof MastersStockRouteImport
      parentRoute: typeof MastersRoute
    }
    '/masters/sites': {
      id: '/masters/sites'
      path: '/sites'
      fullPath: '/masters/sites'
      preLoaderRoute: typeof MastersSitesRouteImport
      parentRoute: typeof MastersRoute
    }
    '/masters/ponds': {
      id: '/masters/ponds'
      path: '/ponds'
      fullPath: '/masters/ponds'
      preLoaderRoute: typeof MastersPondsRouteImport
      parentRoute: typeof MastersRoute
    }
    '/masters/owners': {
      id: '/masters/owners'
      path: '/owners'
      fullPath: '/masters/owners'
      preLoaderRoute: typeof MastersOwnersRouteImport
      parentRoute: typeof MastersRoute
    }
    '/masters/ledgers': {
      id: '/masters/ledgers'
      path: '/ledgers'
      fullPath: '/masters/ledgers'
      preLoaderRoute: typeof MastersLedgersRouteImport
      parentRoute: typeof MastersRoute
    }
    '/masters/costcentres': {
      id: '/masters/costcentres'
      path: '/costcentres'
      fullPath: '/masters/costcentres'
      preLoaderRoute: typeof MastersCostcentresRouteImport
      parentRoute: typeof MastersRoute
    }
    '/masters/buyers': {
      id: '/masters/buyers'
      path: '/buyers'
      fullPath: '/masters/buyers'
      preLoaderRoute: typeof MastersBuyersRouteImport
      parentRoute: typeof MastersRoute
    }
    '/finance/tally': {
      id: '/finance/tally'
      path: '/tally'
      fullPath: '/finance/tally'
      preLoaderRoute: typeof FinanceTallyRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/purchases': {
      id: '/finance/purchases'
      path: '/purchases'
      fullPath: '/finance/purchases'
      preLoaderRoute: typeof FinancePurchasesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/lease': {
      id: '/finance/lease'
      path: '/lease'
      fullPath: '/finance/lease'
      preLoaderRoute: typeof FinanceLeaseRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/harvest': {
      id: '/finance/harvest'
      path: '/harvest'
      fullPath: '/finance/harvest'
      preLoaderRoute: typeof FinanceHarvestRouteImport
      parentRoute: typeof FinanceRoute
    }
  }
}

interface FinanceRouteChildren {
  FinanceHarvestRoute: typeof FinanceHarvestRoute
  FinanceLeaseRoute: typeof FinanceLeaseRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinancePurchasesRoute: typeof FinancePurchasesRoute
  FinanceTallyRoute: typeof FinanceTallyRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceHarvestRoute: FinanceHarvestRoute,
  FinanceLeaseRoute: FinanceLeaseRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinancePurchasesRoute: FinancePurchasesRoute,
  FinanceTallyRoute: FinanceTallyRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface MastersRouteChildren {
  MastersBuyersRoute: typeof MastersBuyersRoute
  MastersCostcentresRoute: typeof MastersCostcentresRoute
  MastersLedgersRoute: typeof MastersLedgersRoute
  MastersOwnersRoute: typeof MastersOwnersRoute
  MastersPondsRoute: typeof MastersPondsRoute
  MastersSitesRoute: typeof MastersSitesRoute
  MastersStockRoute: typeof MastersStockRoute
  MastersSuppliersRoute: typeof MastersSuppliersRoute
  MastersWorkersRoute: typeof MastersWorkersRoute
}

const MastersRouteChildren: MastersRouteChildren = {
  MastersBuyersRoute: MastersBuyersRoute,
  MastersCostcentresRoute: MastersCostcentresRoute,
  MastersLedgersRoute: MastersLedgersRoute,
  MastersOwnersRoute: MastersOwnersRoute,
  MastersPondsRoute: MastersPondsRoute,
  MastersSitesRoute: MastersSitesRoute,
  MastersStockRoute: MastersStockRoute,
  MastersSuppliersRoute: MastersSuppliersRoute,
  MastersWorkersRoute: MastersWorkersRoute,
}

const MastersRouteWithChildren =
  MastersRoute._addFileChildren(MastersRouteChildren)

interface OperationsRouteChildren {
  OperationsAttendanceRoute: typeof OperationsAttendanceRoute
  OperationsCanteenRoute: typeof OperationsCanteenRoute
  OperationsElectricityRoute: typeof OperationsElectricityRoute
  OperationsFeedingRoute: typeof OperationsFeedingRoute
  OperationsVehiclesRoute: typeof OperationsVehiclesRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsAttendanceRoute: OperationsAttendanceRoute,
  OperationsCanteenRoute: OperationsCanteenRoute,
  OperationsElectricityRoute: OperationsElectricityRoute,
  OperationsFeedingRoute: OperationsFeedingRoute,
  OperationsVehiclesRoute: OperationsVehiclesRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRouteWithChildren,
  LoginRoute: LoginRoute,
  MastersRoute: MastersRouteWithChildren,
  OperationsRoute: OperationsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
